#!/bin/bash

#stage all changes

#prompt user for a comit message

if [[ -n $(git status -s) ]]; then
	echo "Uncommited changes"
	git status

	echo -n "Enter a commit message: "
	read commit_message

	git add .

	#commit changes
	git commit -m "$commit_message"

	#push changes
	git push --verbose
else
	echo "No changes to commit"
fi
